# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

pz_core:
    resource: "@PZCoreBundle/Controller/"
    type:     annotation
    prefix:   /

pz_event:
    resource: "@PZEventBundle/Controller/"
    type:     annotation
    prefix:   /event


pz_user:
    resource: "@PZUserBundle/Controller/"
    type:     annotation
    prefix:   /user