<?php

namespace PZ\UserBundle\Repository;

/**
 * MoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoreRepository extends \Doctrine\ORM\EntityRepository
{
}
